services:
  pgdatabase:
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql:rw"
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

  taxi_ingest:
    build:
      context: .
      dockerfile: docker_workshop/pipeline/Dockerfile
    command: >
      --pg-user=root
      --pg-pass=root
      --pg-host=pgdatabase
      --pg-port=5432
      --pg-db=ny_taxi
      --target-table=yellow_taxi_trips_2021_2
      --year=2021
      --month=2
      --chunksize=100000
    depends_on:
      - pgdatabase
volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

